import jsPDF from 'jspdf';
import type { Curriculum, Goal } from '../types/curriculum';

/**
 * Export curriculum to PDF format
 */
export function exportToPDF(curriculum: Curriculum, goal: Goal): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  let yPosition = margin;

  // Header with gradient effect (simulated with text)
  doc.setFillColor(102, 126, 234);
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.text('Brainion Curriculum', margin, 25);

  // Reset text color
  doc.setTextColor(31, 41, 55);
  yPosition = 55;

  // Curriculum metadata
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text(`Topic: ${goal.topic}`, margin, yPosition);
  yPosition += 10;
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(`Duration: ${goal.duration} weeks | Level: ${goal.level}`, margin, yPosition);
  yPosition += 15;

  // Iterate through weeks
  curriculum.weeks.forEach((week) => {
    // Check if we need a new page
    if (yPosition > pageHeight - 40) {
      doc.addPage();
      yPosition = margin;
    }

    // Week header
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(102, 126, 234);
    doc.text(`Week ${week.weekNumber}`, margin, yPosition);
    yPosition += 10;
    doc.setTextColor(31, 41, 55);

    // Days
    week.days.forEach((day, dayIndex) => {
      if (yPosition > pageHeight - 40) {
        doc.addPage();
        yPosition = margin;
      }

      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text(`Day ${dayIndex + 1}: ${day.title}`, margin + 5, yPosition);
      yPosition += 7;

      // Objectives
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      day.objectives.forEach((objective) => {
        if (yPosition > pageHeight - 30) {
          doc.addPage();
          yPosition = margin;
        }
        
        const lines = doc.splitTextToSize(`• ${objective}`, pageWidth - margin * 2 - 10);
        lines.forEach((line: string) => {
          doc.text(line, margin + 10, yPosition);
          yPosition += 5;
        });
      });
      yPosition += 5;
    });

    yPosition += 5;
  });

  // Footer
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(107, 114, 128);
    doc.text(
      `Generated by Brainion | Page ${i} of ${totalPages}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );
  }

  // Download
  const fileName = `${goal.topic.replace(/\s+/g, '_')}_curriculum.pdf`;
  doc.save(fileName);
}

/**
 * Export curriculum to Markdown format
 */
export function exportToMarkdown(curriculum: Curriculum, goal: Goal): string {
  let markdown = `# ${goal.topic} Curriculum\n\n`;
  markdown += `**Duration:** ${goal.duration} weeks  \n`;
  markdown += `**Level:** ${goal.level}  \n`;
  markdown += `**Generated:** ${new Date().toLocaleDateString()}  \n\n`;
  markdown += `---\n\n`;

  curriculum.weeks.forEach((week) => {
    markdown += `## Week ${week.weekNumber}\n\n`;

    week.days.forEach((day, dayIndex) => {
      markdown += `### Day ${dayIndex + 1}: ${day.title}\n\n`;
      markdown += `**Learning Objectives:**\n\n`;
      
      day.objectives.forEach((objective) => {
        markdown += `- ${objective}\n`;
      });
      
      markdown += `\n`;
    });

    markdown += `---\n\n`;
  });

  markdown += `*Generated with ❤️ by Brainion*\n`;

  return markdown;
}

/**
 * Download markdown file
 */
export function downloadMarkdown(curriculum: Curriculum, goal: Goal): void {
  const markdown = exportToMarkdown(curriculum, goal);
  const blob = new Blob([markdown], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${goal.topic.replace(/\s+/g, '_')}_curriculum.md`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Copy markdown to clipboard
 */
export async function copyMarkdownToClipboard(curriculum: Curriculum, goal: Goal): Promise<void> {
  const markdown = exportToMarkdown(curriculum, goal);
  await navigator.clipboard.writeText(markdown);
}
